# Generated by Django 6.0 on 2026-01-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology & Coding'), ('DESIGN', 'Graphics & Design'), ('ACADEMIC', 'Tutoring & Academic'), ('ERRANDS', 'Errands & Laundry'), ('KRA', 'KRA Returns Filing Services'), ('OTHER', 'Other Services')], default='ERRANDS', max_length=20),
        ),
    ]
